### ISSUE TITLE
White background in main chat area - Needs update

### ISSUE THREAD

**Issue by ammarelsh** [laCour/slack-night-mode#160]
<img width="1436" alt="screen shot 2018-04-17 at 8 44 34 am" src="https://user-images.githubusercontent.com/29470505/38880989-d98442ea-421b-11e8-8354-25599dc317c8.png">

Thanks!

**Comment by laCour** [comment]
Can you verify that you've updated to the latest release? This should be fixed.

**Comment by cryocaustik** [comment]
the fix worked for in browser but the issue still exists in desktop

**Comment by ammarelsh** [comment]
Thank you, for some reason in Stylus on Chrome it was saying I was "Up to date", but when I checked https://userstyles.org/styles/117475/slack-night-mode-black there was a later update.

I had to uninstall and then reinstall and it was fixed. Sorry for the false alarm

**Comment by cryocaustik** [comment]
@laCour if you add an `!important` to the `.p-message_pane .c-message_list.c-virtual_list--scrollbar > .c-scrollbar__hider { background: #222; }` section it will fix the issue on desktop as well. 


please let me know if you would rather not update this as it is for desktop; I would be willing to fork dark theme and support it for the desktop application. 

Thanks!


edit: my issue was due to URL caching on rawgit.com; will be updating my docs to use rawgithubusercontent to resolve the issue.

**Comment by zuzusik** [comment]
would be nice to have it fixed on desktop too! thanks!
