### ISSUE TITLE
Message actions has white padding.

### ISSUE THREAD

**Issue by RecursiveFault** [laCour/slack-night-mode#71]
The message actions under the ... button now have white padding.

![messageactions](https://cloud.githubusercontent.com/assets/9141744/16365661/0000dc0c-3bd5-11e6-9378-506d671fdf88.png)

**Comment by laCour** [comment]
The recent update should resolve this issue. You may need to update via [userstyles.org](https://userstyles.org/styles/117475/slack-night-mode-black) if updating through the extension's style management page does not work.

**Comment by RecursiveFault** [comment]
Hm, I completely removed and reinstalled the style and I'm still having the same issue. I'm using Firefox on Win10.

**Comment by laCour** [comment]
I'll look into it tonight, thanks!

**Comment by laCour** [comment]
Narrowed down the issue and fixed it, let me know if the fix works for you. 🍻

**Comment by RecursiveFault** [comment]
Yup! Thank you.
